### ISSUE TITLE
Add queue items to media session

### ISSUE THREAD

**Issue by RaulGw4** [vfsfitvnm/ViMusic#499]
### Feature description

Beeing able to select songs from the watch

### Why do you want this feature?

For example I am riding my bike and want to select a song without the need to pull out my phone.

### Additional information

![Screenshot_20221023_141005_mediacontroller](https://user-images.githubusercontent.com/116492323/197388739-9fe3ccdf-e885-47dd-94ef-19c0bf91d5f5.png)

**Comment by vfsfitvnm** [comment]
Would install this debug apk and tell me if it shows the queue? https://github.com/sriio/ViMusic/releases/tag/lastest

**Comment by RaulGw4** [comment]
> Would install this debug apk and tell me if it shows the queue? https://github.com/sriio/ViMusic/releases/tag/lastest

Only shows the ones on the start screen (the ones you listened to before) but not when you search for a song and give similar ones.

**Comment by vfsfitvnm** [comment]
Sorry I never owned such device so I don't know how things should work. Would you elaborate more?

**Comment by RaulGw4** [comment]
When you listen to something on your phone/tablet a simbol will apeer like the one on the bottom of this picture: ![Screenshot_20221023_144122_sysui.png](https://user-images.githubusercontent.com/116492323/197390098-e6cabf43-dde4-4b1d-a3da-afc9fb4e4db4.png)

When you tap on it it shows the app you will have control over: you can skip songs, go back a song, stop/play and also control the volume of your phone. There is also some information display like the name of the song and the author.
![Screenshot_20221023_144256_mediacontroller.png](https://user-images.githubusercontent.com/116492323/197390733-c2a95647-3d08-471b-9745-0c322ddd3c9a.png)

If you swipe from the bottom the queue menu appers.
While swiping: ![Screenshot_20221023_145835_mediacontroller.png](https://user-images.githubusercontent.com/116492323/197390866-95d55ebb-a6e9-4b94-815b-3710b0f227f6.png)

After swiping: ![Screenshot_20221023_150002_mediacontroller.png](https://user-images.githubusercontent.com/116492323/197390896-9a60f331-69c2-495b-afef-db5e2cec1bb2.png)
From there you can select songs you want to play next.
If you are in a playlist for exemple in YouTube music there will be shown all the songs in that playlist and they will stay in order like you have them in the app and you can come back to them at any time.
![Screenshot_20221023_150410_mediacontroller.png](https://user-images.githubusercontent.com/116492323/197391072-8b9ede80-e6de-4c55-8c98-f1760631ed9e.png)

But if you will search for a song and start playing that song there will be shown all the similar songs to that one you started playing first and the same rules as the one above apply.
![Screenshot_20221023_150518_mediacontroller.png](https://user-images.githubusercontent.com/116492323/197391116-d3cef62f-264b-4a4a-aacf-6192c2a79884.png)

I hope this is enough for you to understand the layout. If you have any questions I will try to reply as quickly as possible. 😄
And keep up the good work! 🦾

**Comment by vfsfitvnm** [comment]
Thanks, got it.

**Comment by vfsfitvnm** [comment]
Ok, I think I got it working. Another question: how do other application handle **large** playlists? Have you ever seen a "go to next page" button?

**Comment by RaulGw4** [comment]
I have tried a random playlist with over 3000 songs and found that there is not a next page but there is a max count as shown in the image.

![Screenshot_20221023_171911_mediacontroller.png](https://user-images.githubusercontent.com/116492323/197397345-6d4002e3-f594-424d-ac0a-6ff518030ff9.png)

Playlist name:
![Screenshot_20221023-171921__01.jpg](https://user-images.githubusercontent.com/116492323/197397362-0fd9ff8e-5ded-4a26-899a-32fc0ca71d64.jpg)

**Comment by vfsfitvnm** [comment]
Thanks. I'll see what to do

**Comment by RaulGw4** [comment]
I went down to the bottom of the playlist on the watch (rip my finger) and found that at an interval of around 2-3 minutes it loads an exact amount of 24 songs (tried 3 times and was the same).

**Comment by vfsfitvnm** [comment]
I couldn't push all the queue because it is an expensive and slow operation. So, I just show 15 songs at time (-7 before the current playing song and +7 after it).

**Comment by RaulGw4** [comment]
Hi again sorry for bothering you so much on this subject. Just trying to help 🙏. 
I installed the update after the fix but there is a new problem. The songs are now visible up to 15 but can't select one to play.

![Screenshot_20221031_215944_mediacontroller.png](https://user-images.githubusercontent.com/116492323/199099911-b4ad1364-1520-4f4c-b879-2e77134e828a.png)

**Comment by vfsfitvnm** [comment]
I will take a look tomorrow

**Comment by vfsfitvnm** [comment]
It should work now, would you test the [debug apk](https://github.com/vfsfitvnm/ViMusic/actions/runs/3367586160)?

**Comment by RaulGw4** [comment]
Sorry about the delay on the debug app i can select songs and are working but the message that you can't skip on the watch still appears.
![Screenshot_20221102_113259_mediacontroller.png](https://user-images.githubusercontent.com/116492323/199455088-07c810e0-de0a-4353-a3db-6dbc9476fce8.png)

**Comment by vfsfitvnm** [comment]
Hmm, that's unfortunate then. I really don't know what's missing.

**Comment by RaulGw4** [comment]
Nice work tho 🦾 
If i find something else I will let you know.

**Comment by vfsfitvnm** [comment]
@RaulGw4 If you could find an open source music player application that works correctly, I could just see what they are doing to make it work. I'm currently using the [media controller test app](https://developer.android.com/guide/topics/media-apps/audio-app/media-controller-test) and everything works from there

**Comment by RaulGw4** [comment]
You are the most lucky person I know.
I was searching on google for music apps, player open source and found a reddit page with a list of 10 apps.
Reddit post (maybe you want to find something in the future): https://www.reddit.com/r/fossdroid/comments/gqaxew/a_curated_list_of_open_source_music_players/?utm_source=share&utm_medium=android_app&utm_name=androidcss&utm_term=1&utm_content=share_button

First app nothing, second as well. At the seventh app I started feeling like no one was interested on this topic. 
Then comes the last app to check out. Opened it and started playing a song and there was it, everything was working perfectly.

App: https://www.reddit.com/r/fossdroid/comments/gqaxew/a_curated_list_of_open_source_music_players/?utm_source=share&utm_medium=android_app&utm_name=androidcss&utm_term=1&utm_content=share_button

It is the shuttle+ app that works not the "free one"

**Comment by vfsfitvnm** [comment]
Thanks! I forgot to add the required `PlaybackState.ACTION_SKIP_TO_QUEUE_ITEM` :sob:
Now it _should_ (:crossed_fingers:) work: apk [here](https://github.com/vfsfitvnm/ViMusic/actions/runs/3383618956)

**Comment by RaulGw4** [comment]
It does work now 🦾
